const getAll = () => async (dispatch) => {
  try {
  } catch (error) {}
};
